title: "Benjamin John Shattock"
description: >- # this means to ignore newlines until "baseurl:"
I am a Undergraduate Computer Science student at Durham University, currently on the MEng Computer Science Course.
baseurl: "/" 
url: "/" 
linkedin_username: https://www.linkedin.com/in/benjamin-shattock/
github_username:  shatt-s

sass:
  sass_dir: _sass

icon: /assets/img/profile-pic.jpeg
